tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/core"

cask_args appdir: "~/Applications"

brew "asdf"
brew "awscli"
brew "direnv"
brew "gh"
brew "git"
brew "jq"
brew "mas"
brew "starship"
brew "stow"

cask "cheatsheet"
cask "deepl"
cask "discord"
cask "docker"
cask "notion"
cask "raycast"
cask "visual-studio-code"
cask "warp"

cask "font-fira-code-nerd-font"
