"$schema" = 'https://starship.rs/config-schema.json'

format = """
$directory\
$git_branch\
$git_state\
$git_status\
$fill\
$cmd_duration\
$line_break\
$character"""

[directory]
truncation_length = 3
truncate_to_repo = false
format = '[$path]($style) '
style = "bold cyan"
repo_root_style = "bold green"
fish_style_pwd_dir_length = 5

[character]
success_symbol = "[❯](green)"
error_symbol = "[❯](red)"

[git_branch]
format = "on [ $branch]($style) "
style = "bold green"

[git_status]
style = "yellow"

[git_state]
style = "bright-black"

[fill]
symbol = " "

[cmd_duration]
min_time = 0
show_milliseconds = true
format = '[\($duration\)]($style) '
style = "bright-black"
