# Prefix key
unbind C-b
set -g prefix C-t
bind-key C-t send-prefix

# Keybind for reload config
bind-key r source-file ~/.config/tmux/tmux.conf \; display-message 'Reloaded!'

# 256 color
set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",xterm-256color:RGB"
set -ag terminal-overrides ",xterm-ghostty:RGB"

# Extended keys
set -s extended-keys always
set -s extended-keys-format csi-u
set -g xterm-keys on
set -as terminal-features ',xterm*:extkeys'
set -as terminal-features ',ghostty*:extkeys'

# Notifications
setw -g monitor-activity on
set -g allow-passthrough on
set -g visual-activity off

# Mause
set -g mouse on

# Copy mode
setw -g mode-keys vi

# Pane border
set -g pane-border-lines single
set -g pane-border-style 'fg=brightblack'
set -g pane-active-border-style "bold,fg=green"
set -g pane-border-status top

# Status bar
set -g status 'on'
set -g status-interval 5
set -g status-position 'top'
set -g status-justify 'right'
set -g status-style 'none,fg=brightblack'
set -g pane-border-format ' #P: #{pane_current_command} '

# Status left
set -g status-left-length 100
set -g status-left-style 'none'
set -g status-left '#{?client_prefix,#[fg=red],} 󰆍  #S  '

# Status right
set -g status-right-style 'none,fg=magenta'
set -g status-right ' #(tmux -V) '

# Window status
setw -g window-status-style 'none'
setw -g window-status-current-style 'bold,fg=green,bg=default'
setw -g window-status-format '  #I: #W  '
setw -g window-status-current-format '  #I: #W  '
setw -g window-status-separator '|'

# Plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'tmux-plugins/tmux-open'
set -g @plugin 'tmux-plugins/tmux-pain-control'
set -g @plugin 'mrjones2014/smart-splits.nvim'

# Install/Run tmux plugin manager
tpm_dir='~/.config/tmux/plugins/tpm'
tpm_repo='https://github.com/tmux-plugins/tpm'
if "test ! -d ${tpm_dir}" \
  "run 'git clone ${tpm_repo} ${tpm_dir}"
run "${tpm_dir}/tpm"
