[theme]
name = "kanagawa"
auto_switch = false

[ui]
prompt_new_tab_name = false

[ui.toast]
delivery = "terminal"

[experimental]
kitty_graphics = true
switch_ascii_input_source_in_prefix = true

[keys]
prefix = "ctrl+b"
focus_pane_left = "alt+h"
focus_pane_down = "alt+j"
focus_pane_up = "alt+k"
focus_pane_right = "alt+l"

[[keys.command]]
key = "alt+H"
type = "shell"
command = "herdr pane resize --current --direction left --amount 0.05"
description = "resize pane left"

[[keys.command]]
key = "alt+J"
type = "shell"
command = "herdr pane resize --current --direction down --amount 0.05"
description = "resize pane down"

[[keys.command]]
key = "alt+K"
type = "shell"
command = "herdr pane resize --current --direction up --amount 0.05"
description = "resize pane up"

[[keys.command]]
key = "alt+L"
type = "shell"
command = "herdr pane resize --current --direction right --amount 0.05"
description = "resize pane right"

[[keys.command]]
key = "alt+g"
type = "pane"
command = "lazygit"
description = "run lazygit"
