"$schema" = 'https://starship.rs/config-schema.json'

format = """
$directory\
$git_branch\
$git_state\
$git_status\
$sudo\
$fill\
$cmd_duration\
$line_break\
$character"""

[directory]
truncation_length = 2
truncate_to_repo = true
format = '[$path]($style)[$read_only]($read_only_style) '
style = "cyan"
read_only = ' 󰌾'
use_logical_path = false

[character]
success_symbol = "[❯](green)"
error_symbol = "[❯](red)"

[git_branch]
format = "on [ $branch]($style) "
style = "bold green"

[git_status]
style = "yellow"

[git_state]
style = "bright-black"

[fill]
symbol = " "

[cmd_duration]
min_time = 0
show_milliseconds = true
format = '[\($duration\)]($style) '
style = "bright-black"

[sudo]
style = 'bold blue'
symbol = ' '
format = 'with [sudo power! $symbol]($style)'
disabled = false
