# yaml-language-server: $schema=https://raw.githubusercontent.com/jesseduffield/lazygit/master/schema/config.json
gui:
  theme:
    selectedLineBgColor:
      - '#727169'
      - bold
git:
  parseEmoji: true
customCommands:
  - key: C
    context: files
    description: Commit with czg
    command: czg
    output: terminal
  - key: A
    context: files
    description: Commit with czg AI
    command: czg ai -N=3
    output: terminal
