onboarding = false

[terminal]
shell_mode = "auto"

[theme]
name = "kanagawa"
auto_switch = false

[ui]
prompt_new_tab_name = false

[ui.toast]
delivery = "terminal"

[experimental]
kitty_graphics = true
switch_ascii_input_source_in_prefix = true

[advanced]
scrollback_limit_bytes = 10000000

[keys]
prefix = "ctrl+b"
focus_pane_left = "alt+h"
focus_pane_down = "alt+j"
focus_pane_up = "alt+k"
focus_pane_right = "alt+l"
next_tab = "alt+tab"
previous_tab = "alt+shift+tab"

[[keys.command]]
key = "alt+g"
type = "pane"
command = "lazygit"
description = "run lazygit"

[[keys.command]]
key = "alt+shift+g"
type = "pane"
command = "gh dash"
description = "run gh-dash"
