name: Flake check
on:
  pull_request:
  push:
    branches:
      - main
permissions:
  contents: read
concurrency:
  group: flake-check-${{ github.ref }}
  cancel-in-progress: true
jobs:
  flake-check:
    runs-on: macos-15
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v7
        with:
          persist-credentials: false
      - uses: cachix/install-nix-action@v31
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - run: nix flake check --accept-flake-config --no-update-lock-file --print-build-logs
